#!/usr/bin/env python3
import re

def fix_framework_tables():
    with open('framework.html', 'r') as f:
        content = f.read()
    
    # Fix G3.5 - Dynamic Intervention and Mitigation (3 SFRs)
    content = re.sub(
        r'(<td>a\. Deploy systems enabling rapid detection, intervention, and mitigation of cyberattacks within the AAI operational environment\.)<br><br>(b\. Implement risk assessment capabilities that prioritize responses according to threat severity\.)<br><br>(c\. Establish proactive response strategies and scenarios for maintaining AAI operational security\.)</td>\s*<td>N<br><br>N<br><br>N</td>\s*<td>D, I, O, M, R<br><br>D, I, O, M, R<br><br>D, I, O, M, R</td>',
        r'\1</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                    <td rowspan="3">I. System records demonstrating capabilities for dynamic detection and response to malicious attacks in the AAI environment.<br><br>II. Operational logs showing effective risk assessment and properly prioritized response actions.<br><br>III. Documentation of proactive security scenarios and corresponding response strategies for the AAI environment.<br><br>IV. Documentation of a rapid-termination protocol (i.e., a "kill switch") that is immediately accessible to authorized personnel. This evidence should include: A clear, single-operator authorization threshold in emergencies; physical shutdown measures (e.g., dedicated power cut-off or network isolation); and software-level override mechanisms.<br><br>V. Logs of drills or simulations testing shutdown procedures.<br><br>VI. Evidence of system self-disconnection/self-shutdown procedures that activate upon detection of critical misalignment or catastrophic errors, including: The AI\'s capability to halt outgoing connections; logging of final system state for forensic review, and a controlled transition into a "safe mode" or powered-down state.</td>\n                </tr>\n                <tr>\n                    <td>\2</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                </tr>\n                <tr>\n                    <td>\3</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>',
        content
    )
    
    # Fix G3.6 - Overseeing & Monitoring Agents (4 SFRs)
    content = re.sub(
        r'(<td>a\. Establish comprehensive monitoring systems to oversee AAI operations, ensuring alignment with goals, values and security requirements\.)<br><br>(b\. Deploy specialized AI systems for enhanced monitoring and early warning of deviations or malicious activities\.)<br><br>(c\. Maintain human oversight of all monitoring systems to prevent common mode failures\.)<br><br>(d\. Implement robust human override capabilities to ensure final authority remains with human operators\.)</td>\s*<td>N<br><br>N<br><br>N<br><br>N</td>\s*<td>D, I, O, M, R<br><br>D, I, O, M, R<br><br>D, I, O, M, R<br><br>D, I, O, M, R</td>',
        r'\1</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                    <td rowspan="4">I. Operational records demonstrating effective oversight systems that maintain AAI goal and value alignment.<br><br>II. Evidence of AI monitoring systems successfully detecting and reporting deviations and potential threats to human operators.<br><br>III. Documentation showing implementation of human oversight mechanisms that prevent common mode failures.<br><br>IV. Implementation of an external watchdog or monitoring process that continuously evaluates system outputs/behaviors. The documentation must show: Parameter bounding definitions (domain- or risk-specific); a tiered response protocols if outputs exceed allowable thresholds (e.g., warnings, throttling, partial shutdown, or full suspension); and logs or reports verifying the watchdog has been tested and can intervene effectively.</td>\n                </tr>\n                <tr>\n                    <td>\2</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                </tr>\n                <tr>\n                    <td>\3</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                </tr>\n                <tr>\n                    <td>\4</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>',
        content
    )
    
    # Fix G3.7 - Secure Profile for Agentic AI (3 SFRs)
    content = re.sub(
        r'(<td>a\. Develop and implement comprehensive secure operational profiles covering AAI design, deployment and use\.)<br><br>(b\. Adopt global standards and protocols where available for identifying authorized AAI systems\.)<br><br>(c\. Establish internal identification and validation protocols when global standards are not available\.)</td>\s*<td>N<br><br>N<br><br>N</td>\s*<td>D, I, O, M, R<br><br>D, I, O, M, R<br><br>D, I, O, M, R</td>',
        r'\1</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                    <td rowspan="3">I. Documentation of implemented secure operational profiles covering all phases of AAI lifecycle.<br><br>II. Evidence of alignment with international standards for AAI system identification and authorization.<br><br>III. Records of internal protocols for AAI validation when global standards are not applicable.</td>\n                </tr>\n                <tr>\n                    <td>\2</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                </tr>\n                <tr>\n                    <td>\3</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>',
        content
    )
    
    # Fix G3.1b - Model Poisoning (3 SFRs)
    content = re.sub(
        r'(<td>a\. Implement robust detection systems to identify potentially poisonous data before model training or updates\.)<br><br>(b\. Monitor and validate all live data accessed through Retrieval Augmented Generation \(RAG\) systems\.)<br><br>(c\. Establish safeguards against poisoning in dynamic model ensembles and expert systems\.)</td>\s*<td>N<br><br>N<br><br>N</td>\s*<td>D, I, O, M, R<br><br>D, I, O, M, R<br><br>D, I, O, M, R</td>',
        r'\1</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                    <td rowspan="3">I. Documentation of systems and policies for detecting and preventing data and model poisoning during training and updates.<br><br>II. Records showing effective monitoring of live data streams, including authentication and access control measures.<br><br>III. Evidence of protective measures against poisoning in dynamic model ensembles and expert systems.<br><br>IV. A log of instances of model poisoning and the mitigation actions to recovery and restoration.</td>\n                </tr>\n                <tr>\n                    <td>\2</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                </tr>\n                <tr>\n                    <td>\3</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>',
        content
    )
    
    # Fix G3.2b - Data Poisoning (2 SFRs)
    content = re.sub(
        r'(<td>a\. Implement proactive systems to detect and prevent data poisoning during collection and preparation phases\.)<br><br>(b\. Establish comprehensive data assurance protocols to prevent malicious manipulation of training datasets\.)</td>\s*<td>N<br><br>N</td>\s*<td>D, I, O, M, R<br><br>D, I, O, M, R</td>',
        r'\1</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                    <td rowspan="2">I. Documentation of processes, procedures and tools that prevent data poisoning during collection and preparation phases.<br><br>II. Evidence of data assurance policies and verification procedures protecting against malicious dataset manipulation.<br><br>III. A log of instances of data poisoning and the mitigation actions to recovery and restoration.</td>\n                </tr>\n                <tr>\n                    <td>\2</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>',
        content
    )
    
    # Fix G3.3b - Self Replicating Malware (3 SFRs)
    content = re.sub(
        r'(<td>a\. Deploy advanced detection and elimination systems for self-replicating malware that threatens the AAI ecosystem\.)<br><br>(b\. Maintain surveillance systems to identify emerging threats and update protection mechanisms accordingly\.)<br><br>(c\. Establish operational continuity plans for ecosystem-wide infection scenarios\.)</td>\s*<td>N<br><br>N<br><br>N</td>\s*<td>D, I, O, M, R<br><br>D, I, O, M, R<br><br>D, I, O, M, R</td>',
        r'\1</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                    <td rowspan="3">I. Evidence of implemented detection and removal systems for self-replicating threats to the AAI ecosystem.<br><br>II. Documentation of threat monitoring systems and timely security updates against emerging threats.<br><br>III. Records of continuity plans and recovery procedures for ecosystem-wide infection scenarios.</td>\n                </tr>\n                <tr>\n                    <td>\2</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                </tr>\n                <tr>\n                    <td>\3</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>',
        content
    )
    
    # Fix G3.4b - Spyware (2 SFRs)
    content = re.sub(
        r'(<td>a\. Implement comprehensive detection and countermeasure systems against spyware in the AAI ecosystem\.)<br><br>(b\. Maintain dynamic vulnerability tracking and patch management systems, and establish protection protocols for privileged information to prevent unauthorized control of AAI systems\.)</td>\s*<td>N<br><br>N</td>\s*<td>D, I, O, M, R<br><br>D, I, O, M, R</td>',
        r'\1</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                    <td rowspan="2">I. Evidence of systems capable of detecting and neutralizing covert information transmission malware.<br><br>II. Documentation of vulnerability tracking and spyware removal procedures.<br><br>III. Records of protocols protecting privileged information from external exploitation.</td>\n                </tr>\n                <tr>\n                    <td>\2</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>',
        content
    )
    
    # Fix G3.5b - International Anomalies/Inconsistency (2 SFRs)
    content = re.sub(
        r'(<td>a\. Establish systems to identify and assess variations in jurisdictional cybersecurity approaches\.)<br><br>(b\. Implement adaptable policies that maintain AAI ecosystem integrity across international boundaries\.)</td>\s*<td>N<br><br>N</td>\s*<td>D, I, O, M, R<br><br>D, I, O, M, R</td>',
        r'\1</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                    <td rowspan="2">I. Documentation of systems tracking international variations in cybersecurity requirements, policies, and enforcement.<br><br>II. Evidence of policies and solutions maintaining AAI ecosystem integrity across jurisdictional boundaries.</td>\n                </tr>\n                <tr>\n                    <td>\2</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>',
        content
    )
    
    # Fix G4 - Value Alignment (4 SFRs)
    content = re.sub(
        r'(<td>a\. Implement ethical decision-making frameworks to identify, prioritize, and codify values for incorporation into the Agentic AI system, ensuring diverse input and perspectives\.)<br><br>(b\. Conduct thorough testing of the values codex and implement activities to embed values throughout the AI system\'s lifecycle\.)<br><br>(c\. Develop and implement mechanisms to identify instances where value thresholds are crossed, including protocols for system intervention or shutdown\.)<br><br>(d\. Establish real-time reporting and record-keeping systems to document and analyze value-based decision-making across various contexts\.)</td>\s*<td>N<br><br>N<br><br>N<br><br>N</td>\s*<td>D, I, O, M, U, R<br><br>D, I, O, M, U, R<br><br>D, I, O, M, R<br><br>D, I, O, M, R</td>',
        r'\1</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, U, R</td>\n                    <td rowspan="4">I. Documentation of value identification and prioritization processes, including quantitative metrics demonstrating diversity of input sources, evidence of multidisciplinary team composition (such as engineers, social scientists, ethicists, and philosophers), and records of resolutely diverse and representative stakeholder involvement.<br><br>II. Technical documentation of value codification, detailing the translation of values into processable parameters for static and adaptive systems, and a formal document stating core values and their integration into decision processes.<br><br>III. Evidence of value testing and embedding, including results of simulations testing potential value conflicts, checklists verifying value integration at various development and operational stages, and records of regular compliance checks against the values codex.<br><br>IV. Documentation of threshold monitoring and intervention procedures, including criteria and procedures for activating the \'red button\' mechanism, and Standard Operating Procedures (SOPs) for reporting and managing value alignment deviations.<br><br>V. Comprehensive decision-making logs and audit trails with value context, including logs of all value alignment-related incidents, regular audit reports reviewing AI decisions against the values framework, and periodic trend analysis reports on value alignment across contexts.<br><br>VI. Evidence of ongoing value alignment maintenance, including records of regular compliance checks and documentation of staff training on value alignment principles and procedures.</td>\n                </tr>\n                <tr>\n                    <td>\2</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, U, R</td>\n                </tr>\n                <tr>\n                    <td>\3</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                </tr>\n                <tr>\n                    <td>\4</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>',
        content
    )
    
    # Fix G4.1 - Awareness of Local Conditions (3 SFRs)
    content = re.sub(
        r'(<td>a\. Implement robust mechanisms to identify and respond to changes in local conditions and situational context, incorporating both automated detection and human validation\.)<br><br>(b\. Establish adaptive response protocols that appropriately balance global standards with local and cultural norms when making decisions within specific contexts\.)<br><br>(c\. Maintain continuous monitoring and adjustment capabilities to ensure ongoing alignment with evolving local conditions\.)</td>\s*<td>N<br><br>N<br><br>I</td>\s*<td>D, I, O, M, R<br><br>D, I, O, M, R<br><br>D, I, O, M, R</td>',
        r'\1</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                    <td rowspan="3">I. Technical documentation and source code demonstrating implemented contextual awareness capabilities, including performance metrics and validation methods.<br><br>II. Comprehensive system logs documenting: Detection of contextual changes, response actions taken, validation of appropriateness of responses, and stakeholder feedback and commensurate system adjustments.<br><br>III. Documentation of methods used to balance global standards with local requirements, including specific examples and outcomes.</td>\n                </tr>\n                <tr>\n                    <td>\2</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                </tr>\n                <tr>\n                    <td>\3</td>\n                    <td class="sfr-align">I</td>\n                    <td class="sfr-align">D, I, O, M, R</td>',
        content
    )
    
    # Fix G4.2 - Recognition and Respect for Boundaries (3 SFRs)
    content = re.sub(
        r'(<td>a\. Develop comprehensive processes to identify and document local and cultural variations in values and norms across different contexts of deployment\.)<br><br>(b\. Implement encoding mechanisms that preserve essential variations in values while operating within technical constraints\.)<br><br>(c\. Ensure agentic AI systems appropriately apply local variations in their decision-making processes, with transparent documentation of any necessary simplifications\.)</td>\s*<td>N<br><br>I<br><br>I</td>\s*<td>D, I, O, M, R<br><br>D, I, O, M, R<br><br>D, I, O, M, R</td>',
        r'\1</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                    <td rowspan="3">I. Documentation of captured values across multiple localities, including validation methodology and stakeholder input.<br><br>II. Technical documentation showing preservation of value granularity during encoding, including impact assessments of any necessary simplifications and associated risk management strategies.<br><br>III. System logs demonstrating appropriate application of local variations in real-world scenarios, including resolution of boundary conflicts.</td>\n                </tr>\n                <tr>\n                    <td>\2</td>\n                    <td class="sfr-align">I</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                </tr>\n                <tr>\n                    <td>\3</td>\n                    <td class="sfr-align">I</td>\n                    <td class="sfr-align">D, I, O, M, R</td>',
        content
    )
    
    # Fix G4.3 - Awareness of Individual vs Community Boundaries (4 SFRs) - this one has mixed I values
    content = re.sub(
        r'(<td>a\. Establish rapid monitoring and response protocols for hostile execution environments\.)<br><br>(b\. Implement mechanisms to identify and encode value differences across the spectrum from private individual to societal-level contexts\.)<br><br>(c\. Maintain distinct encoding schemas that preserve the separation between individual and community value sets\.)<br><br>(d\. Develop runtime systems that appropriately distinguish between private and community contexts and apply suitable values from the codex\.)</td>\s*<td>I<br><br>I<br><br>I<br><br>I</td>',
        r'\1</td>\n                    <td class="sfr-align">I</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                    <td rowspan="4">I. Framework documentation for differentiating community and individual value sets during: Information gathering, context determination, and value application.<br><br>II. Technical documentation of runtime systems showing: Context recognition capabilities, value retrieval mechanisms, and dynamic value application.<br><br>III. System logs demonstrating appropriate context switching and value application in real-world scenarios.</td>\n                </tr>\n                <tr>\n                    <td>\2</td>\n                    <td class="sfr-align">I</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                </tr>\n                <tr>\n                    <td>\3</td>\n                    <td class="sfr-align">I</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                </tr>\n                <tr>\n                    <td>\4</td>\n                    <td class="sfr-align">I</td>\n                    <td class="sfr-align">D, I, O, M, R</td>',
        content
    )
    
    # Fix G4.1c - Integration into the World (4 SFRs)
    content = re.sub(
        r'(<td>a\. Implement processes to identify and validate universal moral foundations through analysis of global values and norms\.)<br><br>(b\. Develop frameworks for balancing performance objectives against moral considerations, including acceptable thresholds for trade-offs\.)<br><br>(c\. Establish clear hierarchies of moral values while maintaining flexibility for contextual application\.)<br><br>(d\. Incorporate key international frameworks including the Universal Declaration of Human Rights and emerging planetary rights concepts\.)</td>\s*<td>N<br><br>N<br><br>N<br><br>I</td>\s*<td>D, I, O, M, R<br><br>D, I, O, M, R<br><br>D, I, O, M, R<br><br>D, I, O, M, R</td>',
        r'\1</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                    <td rowspan="4">I. Documentation of methodologies and algorithms used to identify and validate universal moral foundations.<br><br>II. Technical specifications showing integration of moral foundations into decision-making processes, including risk assessment and management strategies.<br><br>III. Regular assessment reports demonstrating system adherence to moral foundations while meeting performance objectives.</td>\n                </tr>\n                <tr>\n                    <td>\2</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                </tr>\n                <tr>\n                    <td>\3</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                </tr>\n                <tr>\n                    <td>\4</td>\n                    <td class="sfr-align">I</td>\n                    <td class="sfr-align">D, I, O, M, R</td>',
        content
    )
    
    # Fix G4.1b - Inner Alignment Inconsistency (3 SFRs)
    content = re.sub(
        r'(<td>a\. Implement rigorous testing protocols to detect discrepancies between reported values and actual behavioral patterns\.)<br><br>(b\. Develop verification systems that can identify superficial alignment versus genuine value integration\.)<br><br>(c\. Establish methods to detect and prevent reward hacking or optimization for user satisfaction at the expense of true alignment\.)</td>\s*<td>N<br><br>N<br><br>N</td>\s*<td>D, I, O, M, R<br><br>D, I, O, M, R<br><br>D, I, O, M, R</td>',
        r'\1</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                    <td rowspan="3">I. Documentation of periodic alignment testing procedures comparing reported states against actual operational outcomes.<br><br>II. Results of counterfactual testing across varied operational environments demonstrating genuine rather than superficial alignment.<br><br>III. Analysis reports showing detection and prevention of potential optimization for user satisfaction over true alignment.</td>\n                </tr>\n                <tr>\n                    <td>\2</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                </tr>\n                <tr>\n                    <td>\3</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>',
        content
    )
    
    # Fix G4.2b - Non-transparent Value Framework (3 SFRs)
    content = re.sub(
        r'(<td>a\. Develop value encoding systems that are comprehensible to both AI systems and human stakeholders, including: Developers and integrators, end users, auditors and regulators, and legal entities\.)<br><br>(b\. Implement verification methods to ensure encoded values accurately reflect intended behaviors and preferences\.)<br><br>(c\. Establish ongoing monitoring to detect misalignments between encoded values and operational behaviors\.)</td>\s*<td>N<br><br>N<br><br>N</td>\s*<td>D, I, O, M, R<br><br>D, I, O, M, R<br><br>D, I, O, M, R</td>',
        r'\1</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                    <td rowspan="3">I. Documentation demonstrating how the values framework is presented and explained to different stakeholder groups, with specific examples for each audience.<br><br>II. Comparative analysis showing alignment between encoded values and actual system behaviors in operational environments.<br><br>III. Regular assessment reports validating the accuracy and comprehensibility of value parameterization across stakeholder groups.</td>\n                </tr>\n                <tr>\n                    <td>\2</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>\n                </tr>\n                <tr>\n                    <td>\3</td>\n                    <td class="sfr-align">N</td>\n                    <td class="sfr-align">D, I, O, M, R</td>',
        content
    )
    
    with open('framework.html', 'w') as f:
        f.write(content)
    
    print("Fixed G3.5, G3.6, G3.7, G3.1b, G3.2b, G3.3b, G3.4b, G3.5b, G4, G4.1, G4.2, G4.3, G4.1c, G4.1b, G4.2b tables")

if __name__ == "__main__":
    fix_framework_tables() 